apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "hw"
  namespace: "hw"
spec:
  replicas: 15
  template:
    metadata:
      labels:
        app: "hw"
    spec:
      serviceAccountName: s3-reader
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: "hw"
        ports:
        - containerPort: 80
        env:
        - name: NGINX_PORT
          value: "80"
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      # Spin up and init-container
      initContainers:
      - name: install
        image: busybox
        command:
        - sh
        - "-c"
        - "echo \"<h1>Hello World! This is ${HOSTNAME}</h1>\" > /work-dir/index.html;"
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      # Create emptyDir type volume
      volumes:
      - name: workdir
        emptyDir: {}