apiVersion: v1
kind: Service
metadata:
  name: "service-hw"
  namespace: "hw"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "hw"
